//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoraExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int IDventa { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public Nullable<int> IDProducto { get; set; }
        public int Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Product Product { get; set; }
    }
}
